name: Generate Documentation

on:
  push:
    paths:
      - '**/*.py'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    env:
      AWS_REGION : "ap-southeast-2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: arn:aws:iam::168420111683:role/dbla-livedemo-github-oidc 
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ env.AWS_REGION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install boto3
        run: pip3 install boto3==1.34.122

      - name: Generate documentation
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '.py$'); do
            python generate_docs.py "$file" docs/
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m 'Add generated documentation'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
